
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Automated Test Generation - Generated by Lance</title>
            <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
            <link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/themes/prism-okaidia.min.css" rel="stylesheet" />
            <style>                
                body {
                    font-family: 'Roboto', sans-serif;
                    background-color: #f8f9fa;
                    color: #333;
                    margin: 0;
                    padding: 20px;
                    }
                    header {
                        margin-bottom: 20px;
                        text-align: center;
                    }
                    header h1 {
                        margin: 0;
                        font-size: 2.5em;
                        color: #007bff;
                    }
                    header p {
                        margin: 5px 0 0;
                        font-size: 1.2em;
                        color: #6c757d;
                    }
                    table {
                        width: 100%;
                        border-collapse: collapse;
                        box-shadow: 0 2px 3px rgba(0,0,0,0.1);
                        background-color: #fff;
                    }
                    th, td {
                        padding: 15px;
                        text-align: left;
                        border: 1px solid #dee2e6;
                    }
                    th {
                        background-color: #007bff;
                        color: #fff;
                        font-weight: 700;
                    }
                    tr:nth-child(even) {
                        background-color: #f2f2f2;
                    }
                    .status-pass {
                        color: green;
                        font-weight: 700;
                    }
                    .status-fail {
                        color: red;
                        font-weight: 700;
                    }
                    pre {
                        background-color: #282a36 !important;
                        color: #f8f8f2 !important;
                        padding: 10px;
                        border-radius: 5px;
                        overflow: auto;
                    }
                    code {
                        font-family: 'Courier New', Courier, monospace;
                    }
            </style>
        </head>
        <body>
            <header>
                <h1>Test Results</h1>
                <p>Generated by Lance</p>
            </header>
            
            <table>
                <tr>
                    <th>Status</th>
                    <th>Label</th>
                    <th>Reason</th>
                    <th>Exit Code</th>
                    <th>Line Coverage</th>
                    <th>Branch Coverage</th>
                    <th>Stderr</th>
                    <th>Stdout</th>
                    <th>Test</th>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>g_0</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>0.0</td>
                    <td>0.0</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testCreateFromByte(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.154 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testCreateFromByte(DfpTest.java:39)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test the creation of a Dfp instance from a byte value.\n', 'test_name': 'testCreateFromByte\n', 'test_code': '@Test\npublic void testCreateFromByte() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, (byte) 123);\n    assertEquals(123, dfp.mant[0]);\n    assertEquals(1, dfp.sign);\n    assertEquals(0, dfp.exp);\n    assertEquals(Dfp.FINITE, dfp.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>g_0</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>0.0</td>
                    <td>0.0</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testCreateFromLong(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.155 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1234567890> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testCreateFromLong(DfpTest.java:39)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test the creation of a Dfp instance from a long value.\n', 'test_name': 'testCreateFromLong\n', 'test_code': '@Test\npublic void testCreateFromLong() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 1234567890L);\n    assertEquals(1234567890L, dfp.mant[0]);\n    assertEquals(1, dfp.sign);\n    assertEquals(0, dfp.exp);\n    assertEquals(Dfp.FINITE, dfp.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>g_0</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>0.0</td>
                    <td>0.0</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testCreateFromDouble(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.129 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123456> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testCreateFromDouble(DfpTest.java:39)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test the creation of a Dfp instance from a double value.\n', 'test_name': 'testCreateFromDouble\n', 'test_code': '@Test\npublic void testCreateFromDouble() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 123.456);\n    assertEquals(123456, dfp.mant[0]);\n    assertEquals(1, dfp.sign);\n    assertEquals(0, dfp.exp);\n    assertEquals(Dfp.FINITE, dfp.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>g_0</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>0.0</td>
                    <td>0.0</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testCreateFromString(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.175 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123456> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testCreateFromString(DfpTest.java:39)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test the creation of a Dfp instance from a String value.\n', 'test_name': 'testCreateFromString\n', 'test_code': '@Test\npublic void testCreateFromString() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, "123.456");\n    assertEquals(123456, dfp.mant[0]);\n    assertEquals(1, dfp.sign);\n    assertEquals(0, dfp.exp);\n    assertEquals(Dfp.FINITE, dfp.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>g_0</td>
                    <td>Compilation failure</td>
                    <td>1</td>
                    <td>0.0</td>
                    <td>0.0</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell">[ERROR] /home/sijia/test-generation-baseline/guided-test-generation/defects4j-subjects-notests/Math-2f/src/test/java/org/apache/commons/math3/dfp/DfpTest.java:[38,48] incompatible types: possible lossy conversion from int to byte
</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test the creation of a Dfp instance with a non-finite value.\n', 'test_name': 'testCreateNonFinite\n', 'test_code': '@Test\npublic void testCreateNonFinite() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, Dfp.INFINITE, 1);\n    assertEquals(Dfp.INFINITE, dfp.nans);\n    assertEquals(1, dfp.sign);\n    assertEquals(0, dfp.exp);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>g_0</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>0.0</td>
                    <td>0.0</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testAddition(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.13 sec  <<< FAILURE!
java.lang.AssertionError: expected:<579> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testAddition(DfpTest.java:41)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test the addition of two Dfp instances.\n', 'test_name': 'testAddition\n', 'test_code': '@Test\npublic void testAddition() {\n    DfpField field = new DfpField(10);\n    Dfp a = new Dfp(field, 123);\n    Dfp b = new Dfp(field, 456);\n    Dfp result = a.add(b);\n    assertEquals(579, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>g_0</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>0.0</td>
                    <td>0.0</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testSubtraction(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.163 sec  <<< FAILURE!
java.lang.AssertionError: expected:<333> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testSubtraction(DfpTest.java:41)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test the subtraction of two Dfp instances.\n', 'test_name': 'testSubtraction\n', 'test_code': '@Test\npublic void testSubtraction() {\n    DfpField field = new DfpField(10);\n    Dfp a = new Dfp(field, 456);\n    Dfp b = new Dfp(field, 123);\n    Dfp result = a.subtract(b);\n    assertEquals(333, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>g_0</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>0.0</td>
                    <td>0.0</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testMultiplication(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.189 sec  <<< FAILURE!
java.lang.AssertionError: expected:<56088> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testMultiplication(DfpTest.java:41)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test the multiplication of two Dfp instances.\n', 'test_name': 'testMultiplication\n', 'test_code': '@Test\npublic void testMultiplication() {\n    DfpField field = new DfpField(10);\n    Dfp a = new Dfp(field, 123);\n    Dfp b = new Dfp(field, 456);\n    Dfp result = a.multiply(b);\n    assertEquals(56088, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>g_0</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>0.0</td>
                    <td>0.0</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testDivision(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.132 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testDivision(DfpTest.java:41)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test the division of two Dfp instances.\n', 'test_name': 'testDivision\n', 'test_code': '@Test\npublic void testDivision() {\n    DfpField field = new DfpField(10);\n    Dfp a = new Dfp(field, 56088);\n    Dfp b = new Dfp(field, 456);\n    Dfp result = a.divide(b);\n    assertEquals(123, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-PASS">PASS</td>
                    <td>g_0</td>
                    <td></td>
                    <td>0</td>
                    <td>0.0</td>
                    <td>0.0</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test the comparison of two Dfp instances.\n', 'test_name': 'testComparison\n', 'test_code': '@Test\npublic void testComparison() {\n    DfpField field = new DfpField(10);\n    Dfp a = new Dfp(field, 123);\n    Dfp b = new Dfp(field, 456);\n    assertTrue(a.lessThan(b));\n    assertTrue(b.greaterThan(a));\n    assertFalse(a.equals(b));\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>g_0</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>0.0</td>
                    <td>0.0</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testRounding(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.153 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testRounding(DfpTest.java:51)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test the rounding of a Dfp instance.\n', 'test_name': 'testRounding\n', 'test_code': '@Test\npublic void testRounding() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 123.456);\n    Dfp result = dfp.rint();\n    assertEquals(123, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>g_0</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>0.0</td>
                    <td>0.0</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testSquareRoot(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.007 sec  <<< FAILURE!
java.lang.AssertionError: expected:<11> but was:<5498>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testSquareRoot(DfpTest.java:51)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test the square root of a Dfp instance.\n', 'test_name': 'testSquareRoot\n', 'test_code': '@Test\npublic void testSquareRoot() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 123.456);\n    Dfp result = dfp.sqrt();\n    assertEquals(11, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-PASS">PASS</td>
                    <td>g_0</td>
                    <td></td>
                    <td>0</td>
                    <td>0.0</td>
                    <td>0.0</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test the conversion of a Dfp instance to a string.\n', 'test_name': 'testToString\n', 'test_code': '@Test\npublic void testToString() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 123.456);\n    assertEquals("123.456", dfp.toString());\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-PASS">PASS</td>
                    <td>g_0</td>
                    <td></td>
                    <td>0</td>
                    <td>0.0</td>
                    <td>0.0</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test the conversion of a Dfp instance to a double.\n', 'test_name': 'testToDouble\n', 'test_code': '@Test\npublic void testToDouble() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 123.456);\n    assertEquals(123.456, dfp.toDouble(), 0.001);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-PASS">PASS</td>
                    <td>g_0</td>
                    <td></td>
                    <td>0</td>
                    <td>0.0</td>
                    <td>0.0</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test the conversion of a Dfp instance to a split double.\n', 'test_name': 'testToSplitDouble\n', 'test_code': '@Test\npublic void testToSplitDouble() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 123.456);\n    double[] result = dfp.toSplitDouble();\n    assertEquals(123.456, result[0] + result[1], 0.001);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-INFO">INFO</td>
                    <td>g_0</td>
                    <td>193.88531112670898</td>
                    <td>29789</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_1</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testCreateFromByte(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testCreateFromByte(DfpTest.java:75)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp instance is correctly created from a byte value.\n', 'test_name': 'testCreateFromByte\n', 'test_code': '@Test\npublic void testCreateFromByte() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, (byte) 123);\n    assertEquals(123, dfp.mant[0]);\n    assertEquals(1, dfp.sign);\n    assertEquals(0, dfp.exp);\n    assertEquals(Dfp.FINITE, dfp.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_1</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testCreateFromLong(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1234567890> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testCreateFromLong(DfpTest.java:75)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp instance is correctly created from a long value.\n', 'test_name': 'testCreateFromLong\n', 'test_code': '@Test\npublic void testCreateFromLong() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 1234567890L);\n    assertEquals(1234567890L, dfp.mant[0]);\n    assertEquals(1, dfp.sign);\n    assertEquals(0, dfp.exp);\n    assertEquals(Dfp.FINITE, dfp.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_1</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testCreateFromDouble(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123456> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testCreateFromDouble(DfpTest.java:75)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp instance is correctly created from a double value.\n', 'test_name': 'testCreateFromDouble\n', 'test_code': '@Test\npublic void testCreateFromDouble() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 123.456);\n    assertEquals(123456, dfp.mant[0]);\n    assertEquals(1, dfp.sign);\n    assertEquals(0, dfp.exp);\n    assertEquals(Dfp.FINITE, dfp.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_1</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testCreateFromString(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.139 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123456> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testCreateFromString(DfpTest.java:75)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp instance is correctly created from a string value.\n', 'test_name': 'testCreateFromString\n', 'test_code': '@Test\npublic void testCreateFromString() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, "123.456");\n    assertEquals(123456, dfp.mant[0]);\n    assertEquals(1, dfp.sign);\n    assertEquals(0, dfp.exp);\n    assertEquals(Dfp.FINITE, dfp.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-PASS">PASS</td>
                    <td>f_0_1</td>
                    <td></td>
                    <td>0</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp instance is correctly created with a non-finite value.\n', 'test_name': 'testCreateNonFinite\n', 'test_code': '@Test\npublic void testCreateNonFinite() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, Dfp.INFINITE, (byte) 1);\n    assertEquals(Dfp.INFINITE, dfp.nans);\n    assertEquals(1, dfp.sign);\n    assertEquals(0, dfp.exp);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_1</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testAddition(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: expected:<579> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testAddition(DfpTest.java:87)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the addition operation works correctly.\n', 'test_name': 'testAddition\n', 'test_code': '@Test\npublic void testAddition() {\n    DfpField field = new DfpField(10);\n    Dfp a = new Dfp(field, 123);\n    Dfp b = new Dfp(field, 456);\n    Dfp result = a.add(b);\n    assertEquals(579, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_1</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testSubtraction(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: expected:<333> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testSubtraction(DfpTest.java:87)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the subtraction operation works correctly.\n', 'test_name': 'testSubtraction\n', 'test_code': '@Test\npublic void testSubtraction() {\n    DfpField field = new DfpField(10);\n    Dfp a = new Dfp(field, 456);\n    Dfp b = new Dfp(field, 123);\n    Dfp result = a.subtract(b);\n    assertEquals(333, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_1</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testMultiplication(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.168 sec  <<< FAILURE!
java.lang.AssertionError: expected:<56088> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testMultiplication(DfpTest.java:87)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the multiplication operation works correctly.\n', 'test_name': 'testMultiplication\n', 'test_code': '@Test\npublic void testMultiplication() {\n    DfpField field = new DfpField(10);\n    Dfp a = new Dfp(field, 123);\n    Dfp b = new Dfp(field, 456);\n    Dfp result = a.multiply(b);\n    assertEquals(56088, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_1</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testDivision(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.22 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testDivision(DfpTest.java:87)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the division operation works correctly.\n', 'test_name': 'testDivision\n', 'test_code': '@Test\npublic void testDivision() {\n    DfpField field = new DfpField(10);\n    Dfp a = new Dfp(field, 56088);\n    Dfp b = new Dfp(field, 456);\n    Dfp result = a.divide(b);\n    assertEquals(123, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_1</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testRounding(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.008 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testRounding(DfpTest.java:86)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the rounding operation works correctly.\n', 'test_name': 'testRounding\n', 'test_code': '@Test\npublic void testRounding() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 123.456);\n    Dfp result = dfp.rint();\n    assertEquals(123, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_1</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testSquareRoot(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.01 sec  <<< FAILURE!
java.lang.AssertionError: expected:<11> but was:<5498>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testSquareRoot(DfpTest.java:86)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the square root operation works correctly.\n', 'test_name': 'testSquareRoot\n', 'test_code': '@Test\npublic void testSquareRoot() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 123.456);\n    Dfp result = dfp.sqrt();\n    assertEquals(11, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_2</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testCreateFromByte(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testCreateFromByte(DfpTest.java:85)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly creates an instance from a byte value.\n', 'test_name': 'testCreateFromByte\n', 'test_code': '@Test\npublic void testCreateFromByte() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, (byte) 123);\n    assertEquals(123, dfp.mant[0]);\n    assertEquals(1, dfp.sign);\n    assertEquals(0, dfp.exp);\n    assertEquals(Dfp.FINITE, dfp.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_2</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testCreateFromLong(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1234567890> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testCreateFromLong(DfpTest.java:85)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly creates an instance from a long value.\n', 'test_name': 'testCreateFromLong\n', 'test_code': '@Test\npublic void testCreateFromLong() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 1234567890L);\n    assertEquals(1234567890L, dfp.mant[0]);\n    assertEquals(1, dfp.sign);\n    assertEquals(0, dfp.exp);\n    assertEquals(Dfp.FINITE, dfp.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_2</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testCreateFromDouble(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123456> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testCreateFromDouble(DfpTest.java:85)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly creates an instance from a double value.\n', 'test_name': 'testCreateFromDouble\n', 'test_code': '@Test\npublic void testCreateFromDouble() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 123.456);\n    assertEquals(123456, dfp.mant[0]);\n    assertEquals(1, dfp.sign);\n    assertEquals(0, dfp.exp);\n    assertEquals(Dfp.FINITE, dfp.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_2</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testCreateFromString(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123456> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testCreateFromString(DfpTest.java:85)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly creates an instance from a string value.\n', 'test_name': 'testCreateFromString\n', 'test_code': '@Test\npublic void testCreateFromString() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, "123.456");\n    assertEquals(123456, dfp.mant[0]);\n    assertEquals(1, dfp.sign);\n    assertEquals(0, dfp.exp);\n    assertEquals(Dfp.FINITE, dfp.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_2</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testAddition(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected:<579> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testAddition(DfpTest.java:87)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly performs addition.\n', 'test_name': 'testAddition\n', 'test_code': '@Test\npublic void testAddition() {\n    DfpField field = new DfpField(10);\n    Dfp a = new Dfp(field, 123);\n    Dfp b = new Dfp(field, 456);\n    Dfp result = a.add(b);\n    assertEquals(579, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_2</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testSubtraction(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected:<333> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testSubtraction(DfpTest.java:87)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly performs subtraction.\n', 'test_name': 'testSubtraction\n', 'test_code': '@Test\npublic void testSubtraction() {\n    DfpField field = new DfpField(10);\n    Dfp a = new Dfp(field, 456);\n    Dfp b = new Dfp(field, 123);\n    Dfp result = a.subtract(b);\n    assertEquals(333, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_2</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testMultiplication(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected:<56088> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testMultiplication(DfpTest.java:87)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly performs multiplication.\n', 'test_name': 'testMultiplication\n', 'test_code': '@Test\npublic void testMultiplication() {\n    DfpField field = new DfpField(10);\n    Dfp a = new Dfp(field, 123);\n    Dfp b = new Dfp(field, 456);\n    Dfp result = a.multiply(b);\n    assertEquals(56088, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_2</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testDivision(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testDivision(DfpTest.java:87)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly performs division.\n', 'test_name': 'testDivision\n', 'test_code': '@Test\npublic void testDivision() {\n    DfpField field = new DfpField(10);\n    Dfp a = new Dfp(field, 56088);\n    Dfp b = new Dfp(field, 456);\n    Dfp result = a.divide(b);\n    assertEquals(123, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_2</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testRounding(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testRounding(DfpTest.java:86)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly performs rounding.\n', 'test_name': 'testRounding\n', 'test_code': '@Test\npublic void testRounding() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 123.456);\n    Dfp result = dfp.rint();\n    assertEquals(123, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_2</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testSquareRoot(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.007 sec  <<< FAILURE!
java.lang.AssertionError: expected:<11> but was:<5498>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testSquareRoot(DfpTest.java:86)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly performs square root.\n', 'test_name': 'testSquareRoot\n', 'test_code': '@Test\npublic void testSquareRoot() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 123.456);\n    Dfp result = dfp.sqrt();\n    assertEquals(11, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_3</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testCreateFromByte(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testCreateFromByte(DfpTest.java:85)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly initializes from a byte value.\n', 'test_name': 'testCreateFromByte\n', 'test_code': '@Test\npublic void testCreateFromByte() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, (byte) 123);\n    assertEquals(123, dfp.mant[0]);\n    assertEquals(1, dfp.sign);\n    assertEquals(0, dfp.exp);\n    assertEquals(Dfp.FINITE, dfp.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_3</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testCreateFromLong(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1234567890> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testCreateFromLong(DfpTest.java:85)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly initializes from a long value.\n', 'test_name': 'testCreateFromLong\n', 'test_code': '@Test\npublic void testCreateFromLong() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 1234567890L);\n    assertEquals(1234567890L, dfp.mant[0]);\n    assertEquals(1, dfp.sign);\n    assertEquals(0, dfp.exp);\n    assertEquals(Dfp.FINITE, dfp.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_3</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testCreateFromDouble(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123456> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testCreateFromDouble(DfpTest.java:85)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly initializes from a double value.\n', 'test_name': 'testCreateFromDouble\n', 'test_code': '@Test\npublic void testCreateFromDouble() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 123.456);\n    assertEquals(123456, dfp.mant[0]);\n    assertEquals(1, dfp.sign);\n    assertEquals(0, dfp.exp);\n    assertEquals(Dfp.FINITE, dfp.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_3</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testCreateFromString(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123456> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testCreateFromString(DfpTest.java:85)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly initializes from a string value.\n', 'test_name': 'testCreateFromString\n', 'test_code': '@Test\npublic void testCreateFromString() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, "123.456");\n    assertEquals(123456, dfp.mant[0]);\n    assertEquals(1, dfp.sign);\n    assertEquals(0, dfp.exp);\n    assertEquals(Dfp.FINITE, dfp.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_3</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testAddition(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected:<579> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testAddition(DfpTest.java:87)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly performs addition.\n', 'test_name': 'testAddition\n', 'test_code': '@Test\npublic void testAddition() {\n    DfpField field = new DfpField(10);\n    Dfp a = new Dfp(field, 123);\n    Dfp b = new Dfp(field, 456);\n    Dfp result = a.add(b);\n    assertEquals(579, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_3</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testSubtraction(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: expected:<333> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testSubtraction(DfpTest.java:87)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly performs subtraction.\n', 'test_name': 'testSubtraction\n', 'test_code': '@Test\npublic void testSubtraction() {\n    DfpField field = new DfpField(10);\n    Dfp a = new Dfp(field, 456);\n    Dfp b = new Dfp(field, 123);\n    Dfp result = a.subtract(b);\n    assertEquals(333, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_3</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testMultiplication(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.118 sec  <<< FAILURE!
java.lang.AssertionError: expected:<56088> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testMultiplication(DfpTest.java:87)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly performs multiplication.\n', 'test_name': 'testMultiplication\n', 'test_code': '@Test\npublic void testMultiplication() {\n    DfpField field = new DfpField(10);\n    Dfp a = new Dfp(field, 123);\n    Dfp b = new Dfp(field, 456);\n    Dfp result = a.multiply(b);\n    assertEquals(56088, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_3</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testDivision(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testDivision(DfpTest.java:87)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly performs division.\n', 'test_name': 'testDivision\n', 'test_code': '@Test\npublic void testDivision() {\n    DfpField field = new DfpField(10);\n    Dfp a = new Dfp(field, 56088);\n    Dfp b = new Dfp(field, 456);\n    Dfp result = a.divide(b);\n    assertEquals(123, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_3</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testRounding(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected:<123> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testRounding(DfpTest.java:86)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly performs rounding.\n', 'test_name': 'testRounding\n', 'test_code': '@Test\npublic void testRounding() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 123.456);\n    Dfp result = dfp.rint();\n    assertEquals(123, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-FAIL">FAIL</td>
                    <td>f_0_3</td>
                    <td>Test failures</td>
                    <td>1</td>
                    <td>48.54</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell"> - in org.apache.commons.math3.dfp.DfpTest
testSquareRoot(org.apache.commons.math3.dfp.DfpTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: expected:<11> but was:<5498>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at org.apache.commons.math3.dfp.DfpTest.testSquareRoot(DfpTest.java:86)</code></pre></td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the Dfp class correctly performs square root.\n', 'test_name': 'testSquareRoot\n', 'test_code': '@Test\npublic void testSquareRoot() {\n    DfpField field = new DfpField(10);\n    Dfp dfp = new Dfp(field, 123.456);\n    Dfp result = dfp.sqrt();\n    assertEquals(11, result.mant[0]);\n    assertEquals(1, result.sign);\n    assertEquals(0, result.exp);\n    assertEquals(Dfp.FINITE, result.nans);\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-INFO">INFO</td>
                    <td>f_0</td>
                    <td>579.3344473838806</td>
                    <td>109944</td>
                    <td>49.18</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                
                <tr>
                    <td class="status-PASS">PASS</td>
                    <td>g_1</td>
                    <td></td>
                    <td>0</td>
                    <td>49.18</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the function returns the correct output for a specific scenario\n', 'test_name': 'testSpecificScenario\n', 'test_code': '@Test\npublic void testSpecificScenario() {\n    // test implementation\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-PASS">PASS</td>
                    <td>g_1</td>
                    <td></td>
                    <td>0</td>
                    <td>49.18</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-python">{'test_behavior': 'Test that the function handles a specific edge case correctly\n', 'test_name': 'testEdgeCase\n', 'test_code': '@Test\npublic void testEdgeCase() {\n    // test implementation\n}\n', 'new_imports_code': 'import static org.junit.Assert.*;\nimport org.junit.Test;\n'}</code></pre></td>
                </tr>
                
                <tr>
                    <td class="status-INFO">INFO</td>
                    <td>g_1</td>
                    <td>37.75736474990845</td>
                    <td>39444</td>
                    <td>49.18</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                
                <tr>
                    <td class="status-INFO">INFO</td>
                    <td>f_1</td>
                    <td>45.03027582168579</td>
                    <td>39444</td>
                    <td>49.18</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                
                <tr>
                    <td class="status-INFO">INFO</td>
                    <td></td>
                    <td></td>
                    <td>0</td>
                    <td>49.18</td>
                    <td>40.62</td>
                    <td>&nbsp;</td>
                    <td><pre><code class="language-shell">{'divide_5646_7': 2, 'divide_5646_6': 1, 'add_3795_6': 2, 'add_3795_15': 1, 'multiply_4735_6': 2, 'multiply_4735_11': 1, 'trunc_3049_14': 1, 'trunc_3049_9': 1, 'round_4472_11': 1, 'round_4472_6': 1, 'toDouble_8797_12': 2, 'toDouble_8797_9': 1, 'sqrt_6972_4': 2, 'sqrt_6972_8': 1, 'dfp2string_7768_8': 1, 'dfp2string_7768_2': 1, 'nextAfter_8454_9': 1, 'nextAfter_8454_8': 1, 'dfp2sci_7395_9': 2, 'dfp2sci_7395_7': 1, 'dotrap_8094_4': 2, 'divide_6673_4': 2, 'divide_6673_8': 1, 'align_1861_7': 2, 'intValue_3393_4': 1, 'power10_3598_3': 1, 'intLog10_3532_2': 2, 'toString_7343_3': 1, 'lessThan_2020_2': 2, 'greaterThan_2125_2': 2, 'greaterThan_2125_1': 1, 'equals_2565_1': 2, 'multiply_5329_2': 2, 'signum_9295_2': 2, 'atan2_9713_2': 2, 'linearCombination_10001_2': 1, 'linearCombination_10080_2': 1, 'newInstance_1622_1': 2, 'negativeOrNull_2230_1': 2, 'strictlyNegative_2289_1': 2, 'positiveOrNull_2347_1': 2, 'strictlyPositive_2406_1': 2, 'unequal_2654_0': 2, 'remainder_2996_1': 2, 'copySign_9326_1': 2, 'copySign_9366_0': 2, 'divide_5646_17': 1, 'add_3795_5': 1, 'multiply_4735_14': 1, 'trunc_3049_13': 1, 'trunc_3049_1': 1, 'round_4472_9': 1, 'round_4472_3': 1, 'toDouble_8797_2': 1, 'sqrt_6972_9': 1, 'dfp2string_7768_10': 1, 'nextAfter_8454_10': 1, 'nextAfter_8454_6': 1, 'dfp2sci_7395_8': 1, 'dotrap_8094_3': 1, 'divide_6673_1': 1, 'align_1861_6': 1, 'intValue_3393_0': 1, 'power10_3598_0': 1, 'intLog10_3532_1': 1, 'toString_7343_2': 1, 'lessThan_2020_1': 1, 'equals_2565_2': 1, 'linearCombination_10001_1': 1, 'linearCombination_10080_1': 1, 'newInstance_1622_0': 1, 'copySign_9326_0': 1, 'copySign_9366_1': 1}</code></pre></td>
                    <td>&nbsp;</td>
                </tr>
                
            </table>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/prism.min.js"></script>
        </body>
        </html>
        